version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: organization_directory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
